version: "3.9"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "8088:80" # Local/Remote, From host/Inside container
    volumes:
      - ./:/var/www/docker2.mostafahub.com
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_php
    volumes:
      - ./:/var/www/docker2.mostafahub.com
    ports:
      - "9000:9000"
    networks:
      - laravel