name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Connect and configurations
      uses: appleboy/ssh-action@v0.1.5
      with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            cd /var/www/docker2.mostafahub.com
            rm -rf /var/www/docker2.mostafahub.com/{*,.*}
            git clone https://github.com/mostafaaminflakes/Laravel-ToDo-App.git /var/www/docker2.mostafahub.com
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan key:generate
            mysql -u${{secrets.DB_USERNAME}} -h127.0.0.1 -p${{secrets.DB_PASSWORD}} -e 'CREATE DATABASE IF NOT EXISTS ${{secrets.DB_NAME}};'
            
  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Laravel migrate
      run: php artisan migrate --force
