name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: SSH Remote Connect and Configurations
      uses: appleboy/ssh-action@v0.1.5
      with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |        
            mysql -u${{secrets.DB_USERNAME}} -h127.0.0.1 -p${{secrets.DB_PASSWORD}} -e 'CREATE DATABASE IF NOT EXISTS ${{secrets.DB_NAME}};'
            cd /var/www/docker2.mostafahub.com
            rm -rf /var/www/docker2.mostafahub.com/{*,.*}
            git clone https://github.com/mostafaaminflakes/Laravel-ToDo-App.git /var/www/docker2.mostafahub.com
    - name: LS -LA
      run: |
        ls -la
        php --version
    - name: Laravel Setup
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        composer install -q --no-ansi --no-scripts --no-progress --no-interaction --prefer-dist --optimize-autoloader
        php artisan key:generate
        chmod -R 777 storage bootstrap/cache
        php artisan migrate:fresh --force
