name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Connect
      uses: appleboy/ssh-action@v0.1.5
      with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            whoami
            ls -al
